### ISSUE TITLE
Forecast Scraper

### ISSUE THREAD

**Issue by g-gar** [g-gar/traveloh#30]

**Comment by franbarbeito** [comment]
Creado scraper para el tiempo meteorológico del aeropuerto Madrid-Barajas.
Se adjunta también al archivo csv correspondiente para su funcionamiento.

Fuente: https://www.tutiempo.net/madrid-barajas.html?datos=ultimas-24-horas
Output: Hora, condición meteorologica, temperatura, viento, humedad, presion
